//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirLineBookingSystemProject_Group03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI_TIET_CHUYENBAY
    {
        public int ID { get; set; }
        public string MACHUYENBAY { get; set; }
        public string MAHANGVE { get; set; }
        public string MALOAIVE { get; set; }
        public decimal GIA { get; set; }
        public Nullable<int> SOLUONGGHE { get; set; }
    
        public virtual CHUYENBAY CHUYENBAY { get; set; }
        public virtual HANGVE HANGVE { get; set; }
        public virtual LOAIVE LOAIVE { get; set; }
    }
}
