//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirLineBookingSystemProject_Group03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUYENBAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHUYENBAY()
        {
            this.DATVEs = new HashSet<DATVE>();
            this.GIOHANGs = new HashSet<GIOHANG>();
            this.CHI_TIET_CHUYENBAY = new HashSet<CHI_TIET_CHUYENBAY>();
        }
    
        public string MACHUYENBAY { get; set; }
        public string MATUYENBAY { get; set; }
        public string MAHANG { get; set; }
        public Nullable<int> SOLUONGGHE { get; set; }
        public Nullable<int> THOIGIANDUNG { get; set; }
        public Nullable<System.DateTime> THOIGIANXUATPHAT { get; set; }
        public Nullable<System.DateTime> THOIGIANDEN { get; set; }
    
        public virtual HANGHANGKHONG HANGHANGKHONG { get; set; }
        public virtual TUYENBAY TUYENBAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATVE> DATVEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIOHANG> GIOHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHI_TIET_CHUYENBAY> CHI_TIET_CHUYENBAY { get; set; }
    }
}
