//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirLineBookingSystemProject_Group03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHGIA
    {
        public string ID { get; set; }
        public string MAKH { get; set; }
        public string MAHANG { get; set; }
        public Nullable<int> SOSAO { get; set; }
        public string NOIDUNG { get; set; }
        public Nullable<System.DateTime> NGAYDG { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual HANGHANGKHONG HANGHANGKHONG { get; set; }
    }
}
