//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirLineBookingSystemProject_Group03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIOHANG
    {
        public string ID { get; set; }
        public string MAKH { get; set; }
        public string MACHUYENBAY { get; set; }
        public string LOAIVE { get; set; }
        public string HANGVE { get; set; }
        public Nullable<decimal> GIATIEN { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<System.DateTime> NGAYTHEM { get; set; }
        public string MAKHUYENMAI { get; set; }
        public Nullable<decimal> GIATIEN_SAUKM { get; set; }
    
        public virtual CHUYENBAY CHUYENBAY { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual KHUYENMAI KHUYENMAI { get; set; }
    }
}
