//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirLineBookingSystemProject_Group03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANGVE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HANGVE()
        {
            this.CHI_TIET_CHUYENBAY = new HashSet<CHI_TIET_CHUYENBAY>();
        }
    
        public string MAHANGVE { get; set; }
        public string TENHANGVE { get; set; }
        public string TIENICH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHI_TIET_CHUYENBAY> CHI_TIET_CHUYENBAY { get; set; }
    }
}
