//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirLineBookingSystemProject_Group03.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QUANLYBANVEMAYBAY6Entities : DbContext
    {
        public QUANLYBANVEMAYBAY6Entities()
            : base("name=QUANLYBANVEMAYBAY6Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHUYENBAY> CHUYENBAYs { get; set; }
        public virtual DbSet<DANHGIA> DANHGIAs { get; set; }
        public virtual DbSet<DATVE> DATVEs { get; set; }
        public virtual DbSet<GIOHANG> GIOHANGs { get; set; }
        public virtual DbSet<HANGHANGKHONG> HANGHANGKHONGs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<QUANLY> QUANLies { get; set; }
        public virtual DbSet<SANBAY> SANBAYs { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<THANHTOAN> THANHTOANs { get; set; }
        public virtual DbSet<TUYENBAY> TUYENBAYs { get; set; }
        public virtual DbSet<VE> VEs { get; set; }
        public virtual DbSet<CHI_TIET_CHUYENBAY> CHI_TIET_CHUYENBAY { get; set; }
        public virtual DbSet<HANGVE> HANGVEs { get; set; }
        public virtual DbSet<LOAIVE> LOAIVEs { get; set; }
        public virtual DbSet<KHUYENMAI> KHUYENMAIs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual int PR_DATVE(string mAKH, string mACHUYENBAY, Nullable<int> sOLUONG, Nullable<double> gIATIENMOIVE, string lOAIVE, string hANGVE)
        {
            var mAKHParameter = mAKH != null ?
                new ObjectParameter("MAKH", mAKH) :
                new ObjectParameter("MAKH", typeof(string));
    
            var mACHUYENBAYParameter = mACHUYENBAY != null ?
                new ObjectParameter("MACHUYENBAY", mACHUYENBAY) :
                new ObjectParameter("MACHUYENBAY", typeof(string));
    
            var sOLUONGParameter = sOLUONG.HasValue ?
                new ObjectParameter("SOLUONG", sOLUONG) :
                new ObjectParameter("SOLUONG", typeof(int));
    
            var gIATIENMOIVEParameter = gIATIENMOIVE.HasValue ?
                new ObjectParameter("GIATIENMOIVE", gIATIENMOIVE) :
                new ObjectParameter("GIATIENMOIVE", typeof(double));
    
            var lOAIVEParameter = lOAIVE != null ?
                new ObjectParameter("LOAIVE", lOAIVE) :
                new ObjectParameter("LOAIVE", typeof(string));
    
            var hANGVEParameter = hANGVE != null ?
                new ObjectParameter("HANGVE", hANGVE) :
                new ObjectParameter("HANGVE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_DATVE", mAKHParameter, mACHUYENBAYParameter, sOLUONGParameter, gIATIENMOIVEParameter, lOAIVEParameter, hANGVEParameter);
        }
    
        public virtual int PROC_HuyDatVe(string maDatVe)
        {
            var maDatVeParameter = maDatVe != null ?
                new ObjectParameter("MaDatVe", maDatVe) :
                new ObjectParameter("MaDatVe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PROC_HuyDatVe", maDatVeParameter);
        }
    
        public virtual ObjectResult<PROC_TimChuyenBay_Result> PROC_TimChuyenBay(string thanhPhoDi, string thanhPhoDen, Nullable<System.DateTime> ngayBay)
        {
            var thanhPhoDiParameter = thanhPhoDi != null ?
                new ObjectParameter("ThanhPhoDi", thanhPhoDi) :
                new ObjectParameter("ThanhPhoDi", typeof(string));
    
            var thanhPhoDenParameter = thanhPhoDen != null ?
                new ObjectParameter("ThanhPhoDen", thanhPhoDen) :
                new ObjectParameter("ThanhPhoDen", typeof(string));
    
            var ngayBayParameter = ngayBay.HasValue ?
                new ObjectParameter("NgayBay", ngayBay) :
                new ObjectParameter("NgayBay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_TimChuyenBay_Result>("PROC_TimChuyenBay", thanhPhoDiParameter, thanhPhoDenParameter, ngayBayParameter);
        }
    
        public virtual int SP_BackupDiff()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_BackupDiff");
        }
    
        public virtual int SP_BackupFull()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_BackupFull");
        }
    
        public virtual int SP_BackupLog()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_BackupLog");
        }
    
        public virtual ObjectResult<sp_GetDatVe_Result> sp_GetDatVe(string mAKH, string tRANGTHAI)
        {
            var mAKHParameter = mAKH != null ?
                new ObjectParameter("MAKH", mAKH) :
                new ObjectParameter("MAKH", typeof(string));
    
            var tRANGTHAIParameter = tRANGTHAI != null ?
                new ObjectParameter("TRANGTHAI", tRANGTHAI) :
                new ObjectParameter("TRANGTHAI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetDatVe_Result>("sp_GetDatVe", mAKHParameter, tRANGTHAIParameter);
        }
    
        public virtual ObjectResult<sp_SearchKhachHang_Result> sp_SearchKhachHang(string mAKH, string hOTEN, string sDT, string cCCD, string dIACHI)
        {
            var mAKHParameter = mAKH != null ?
                new ObjectParameter("MAKH", mAKH) :
                new ObjectParameter("MAKH", typeof(string));
    
            var hOTENParameter = hOTEN != null ?
                new ObjectParameter("HOTEN", hOTEN) :
                new ObjectParameter("HOTEN", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var cCCDParameter = cCCD != null ?
                new ObjectParameter("CCCD", cCCD) :
                new ObjectParameter("CCCD", typeof(string));
    
            var dIACHIParameter = dIACHI != null ?
                new ObjectParameter("DIACHI", dIACHI) :
                new ObjectParameter("DIACHI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SearchKhachHang_Result>("sp_SearchKhachHang", mAKHParameter, hOTENParameter, sDTParameter, cCCDParameter, dIACHIParameter);
        }
    
        public virtual ObjectResult<sp_SearchVe_AllStatus_Result> sp_SearchVe_AllStatus(string mAVE, string hANGVE, string lOAIVE)
        {
            var mAVEParameter = mAVE != null ?
                new ObjectParameter("MAVE", mAVE) :
                new ObjectParameter("MAVE", typeof(string));
    
            var hANGVEParameter = hANGVE != null ?
                new ObjectParameter("HANGVE", hANGVE) :
                new ObjectParameter("HANGVE", typeof(string));
    
            var lOAIVEParameter = lOAIVE != null ?
                new ObjectParameter("LOAIVE", lOAIVE) :
                new ObjectParameter("LOAIVE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SearchVe_AllStatus_Result>("sp_SearchVe_AllStatus", mAVEParameter, hANGVEParameter, lOAIVEParameter);
        }
    
        public virtual int sp_UpdateVe(string mAVE, string mASANBAY, Nullable<double> gIATIEN, string lOAIVE, string hANGVE, string mAGHE)
        {
            var mAVEParameter = mAVE != null ?
                new ObjectParameter("MAVE", mAVE) :
                new ObjectParameter("MAVE", typeof(string));
    
            var mASANBAYParameter = mASANBAY != null ?
                new ObjectParameter("MASANBAY", mASANBAY) :
                new ObjectParameter("MASANBAY", typeof(string));
    
            var gIATIENParameter = gIATIEN.HasValue ?
                new ObjectParameter("GIATIEN", gIATIEN) :
                new ObjectParameter("GIATIEN", typeof(double));
    
            var lOAIVEParameter = lOAIVE != null ?
                new ObjectParameter("LOAIVE", lOAIVE) :
                new ObjectParameter("LOAIVE", typeof(string));
    
            var hANGVEParameter = hANGVE != null ?
                new ObjectParameter("HANGVE", hANGVE) :
                new ObjectParameter("HANGVE", typeof(string));
    
            var mAGHEParameter = mAGHE != null ?
                new ObjectParameter("MAGHE", mAGHE) :
                new ObjectParameter("MAGHE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateVe", mAVEParameter, mASANBAYParameter, gIATIENParameter, lOAIVEParameter, hANGVEParameter, mAGHEParameter);
        }
    }
}
