//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirLineBookingSystemProject_Group03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHTOAN
    {
        public string MATT { get; set; }
        public string MAVE { get; set; }
        public Nullable<System.DateTime> NGAYGD { get; set; }
        public string PHUONGTHUCTT { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
    
        public virtual VE VE { get; set; }
    }
}
