//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirLineBookingSystemProject_Group03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VE()
        {
            this.THANHTOANs = new HashSet<THANHTOAN>();
        }
    
        public string MAVE { get; set; }
        public string MADATVE { get; set; }
        public string MASANBAY { get; set; }
        public Nullable<double> GIATIEN { get; set; }
        public string LOAIVE { get; set; }
        public string HANGVE { get; set; }
        public string MAGHE { get; set; }
    
        public virtual DATVE DATVE { get; set; }
        public virtual SANBAY SANBAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THANHTOAN> THANHTOANs { get; set; }
    }
}
